### ISSUE TITLE
Create the app design

### ISSUE THREAD

**Issue by suba-krishnan** [chingu-voyages/v42-bears-team-38#16]
Design idea. Please add your thoughts and comments .

App title: Prescription Manager
Tabs on the header for: New Patient, Existing Patient and Inventory search
**New Patient:**

- When the button is clicked, open the form with fields and OK button to save

**Existing patient**
-On click, list all the existing patients with a divider after each. Add a vertical scrollbar
- On Click on a patient name. Display a table: with Medication, dosage and refill date
- 
**Inventory search**
- Use a textbox and displays a suggestion box upon entering 3 characters. 

- Please use a responsive font throughout. 
-  Header font color and button bg: #964f6b
- Rest of the page: #ffffff

**Comment by davidmetcal** [comment]
Here is the start of a framework to the screens we might want to include:

https://www.figma.com/file/TVpWzOKFh2xr7JtOLhev7g/Perscription-Patient-Form?node-id=0%3A1&t=08GLIQuBDvsf0Tea-1

**Comment by davidmetcal** [comment]
<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);" width="800" height="450" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FTVpWzOKFh2xr7JtOLhev7g%2FPerscription-Patient-Form%3Fnode-id%3D0%253A1%26t%3D08GLIQuBDvsf0Tea-1" allowfullscreen></iframe>
