### ISSUE TITLE
Develop DB /api to pull data

### ISSUE THREAD

**Issue by suba-krishnan** [chingu-voyages/v42-bears-team-38#17]
**__Task Description__**
Describe the task to be completed.

**__Technical Considerations__**
Include any technical considerations including architecture (e.g. API), required libraries, etc.

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by davidmetcal** [comment]
Initial outline of the API for creating patient, prescriber and prescription developed. It may be that we need to expand the data tables depending on the features required.
